name: Backend Main Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: '1.17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean install
      env:
        JWT_ACCESS_KEY: ${{ secrets.JWT_ACCESS_KEY }}
        JWT_REFRESH_KEY: ${{ secrets.JWT_REFRESH_KEY }}
        JWT_ACCESS_VALID_MINUTES: ${{ vars.JWT_ACCESS_VALID_MINUTES }}
        JWT_REFRESH_VALID_MINUTES: ${{ vars.JWT_REFRESH_VALID_MINUTES }}
        URI_USER_SERVICE: ${{ vars.URI_USER_SERVICE }}
        URI_DICTIONARY_SERVICE: ${{ vars.URI_DICTIONARY_SERVICE }}
        URI_ML_SERVICE: ${{ vars.URI_ML_SERVICE }}
        BASE_PREFIX: ${{ vars.BASE_PREFIX }}
        AWS_STAGE: ${{ secrets.AWS_STAGE }}
        URI_AWS_SERVICES: ${{ secrets.URI_AWS_SERVICES }}
